---
- name: Windows/Linux: System Update (Debian/RedHat) - run on all hosts
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      register: apt_update_result
      ignore_errors: yes

    - name: Upgrade packages (Debian/Ubuntu)
      apt:
        upgrade: dist
        autoremove: yes
      when: ansible_os_family == "Debian"
      register: upgrade_result
      ignore_errors: yes

    - name: Check dnf update (RedHat family) - simulate check-update
      command: dnf check-update
      when: ansible_os_family == "RedHat"
      register: simulate_dnf
      failed_when: false
      changed_when: false

    - name: Run dnf upgrade (RedHat family)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      register: upgrade_result
      ignore_errors: yes

    - name: Prüfen ob Reboot erforderlich
      stat:
        path: /var/run/reboot-required
      register: reboot_file
      ignore_errors: yes

    - name: Set host summary fact (wird später für das Summary genutzt)
      set_fact:
        host_update_summary:
          host: "{{ inventory_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          changed: "{{ (upgrade_result.changed | default(false)) | bool }}"
          failed: "{{ (upgrade_result.failed | default(false)) | bool }}"
          reboot_required: "{{ reboot_file.stat.exists | default(false) }}"
          msg_short: >
            {% if (upgrade_result is defined) %}
              {% if upgrade_result.changed %}Updates installiert{% else %}keine Updates{% endif %}
            {% else %}
              kein Ergebnis
            {% endif %}
      # host facts should remain available via hostvars

    - name: Save debug info locally (optional)
      debug:
        var: host_update_summary
      when: false

- name: Sammle Ergebnisse und sende ein zusammenfassendes Discord-Summary (einmal)
  hosts: localhost
  gather_facts: no
  run_once: true

  tasks:
    - name: Sicherstellen dass discord_webhook gesetzt ist
      assert:
        that:
          - discord_webhook is defined
        fail_msg: >
          "discord_webhook ist nicht gesetzt. Lege die Webhook URL in Inventory-Variablen oder als extra var fest."
      run_once: true

    - name: Baue Liste mit Host-Zusammenfassungen
      set_fact:
        summary_lines: "{{ summary_lines | default([]) + [ single_line ] }}"
      vars:
        single_line: >-
          **{{ hostvars[item].host_update_summary.host }}** — 
          {{ hostvars[item].host_update_summary.os }} — 
          {% if hostvars[item].host_update_summary.failed %}❌ Fehler{% elif hostvars[item].host_update_summary.changed %}✅ Updates installiert{% else %}ℹ️ Keine Updates{% endif %}{% if hostvars[item].host_update_summary.reboot_required %} — 🔁 Reboot erforderlich{% endif %}
      loop: "{{ groups['all'] }}"
      loop_control:
        label: "{{ item }}"

    - name: Falls keine Hosts in Inventory, füge Info hinzu
      set_fact:
        summary_lines: ["Keine Hosts im Inventory gefunden."]
      when: summary_lines is not defined or summary_lines | length == 0

    - name: Baue Discord Payload
      set_fact:
        discord_payload:
          content: ""
          embeds:
            - title: "Täglicher Update-Summary"
              description: "Zusammenfassung der Updates für {{ ansible_date_time.date | default(lookup('pipe','date +%F')) }}"
              fields:
                - name: "Anzahl Hosts"
                  value: "{{ groups['all'] | length }}"
                  inline: true
                - name: "Zeit"
                  value: "{{ lookup('pipe','date +%H:%M:%S') }}"
                  inline: true
                - name: "Details"
                  value: "{{ summary_lines | join('\\n') }}"
                  inline: false
              timestamp: "{{ lookup('pipe','date --iso-8601=seconds') }}"
      no_log: false

    - name: Send summary to Discord webhook
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ discord_payload | to_json }}"
        status_code: [200,204]
        body_format: json
      register: discord_result
      failed_when: discord_result.status not in [200,204]

    - name: Debug: Discord Ergebnis
      debug:
        var: discord_result
      when: discord_result is defined
