---
- name: "Windows/Linux: System Update (Debian/RedHat) - run on all hosts"
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: "Update apt cache (Debian/Ubuntu)"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      register: apt_update_result

    - name: "Upgrade packages (Debian/Ubuntu)"
      apt:
        upgrade: dist
        autoremove: yes
      when: ansible_os_family == "Debian"
      register: upgrade_result
      ignore_errors: yes

    - name: "Check dnf update (RedHat family) - simulate check-update"
      command: dnf check-update
      when: ansible_os_family == "RedHat"
      register: simulate_dnf
      failed_when: false
      changed_when: false

    - name: "Run dnf upgrade (RedHat family)"
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      register: upgrade_result
      ignore_errors: yes

    - name: "Prüfen ob Reboot erforderlich"
      stat:
        path: /var/run/reboot-required
      register: reboot_file
      ignore_errors: yes

    - name: "Set host summary fact"
      set_fact:
        host_update_summary:
          host: "{{ inventory_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          changed: "{{ (upgrade_result.changed | default(false)) | bool }}"
          failed: "{{ (upgrade_result.failed | default(false)) | bool }}"
          reboot_required: "{{ reboot_file.stat.exists | default(false) }}"

- name: "Sammle Ergebnisse und sende ein zusammenfassendes Discord-Summary (einmal)"
  hosts: localhost
  gather_facts: no
  run_once: true

  tasks:
    - name: "Sicherstellen dass discord_webhook gesetzt ist"
      assert:
        that:
          - discord_webhook is defined
        fail_msg: "discord_webhook ist nicht gesetzt. Lege die Webhook URL in Inventory-Variablen oder als extra var fest."
      run_once: true

    - name: "Baue Liste mit Host-Zusammenfassungen"
      set_fact:
        summary_lines: "{{ summary_lines | default([]) + [ single_line ] }}"
      vars:
        single_line: >
