---
- name: "System-Updates durchführen (Debian/RedHat) und Host-Ergebnisse sammeln"
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    max_pkg_preview: 8

  tasks:
    - name: "APT: Cache aktualisieren (Debian/Ubuntu)"
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      register: apt_update_result
      failed_when: false

    - name: "APT: Upgrade durchführen (Debian/Ubuntu)"
      apt:
        upgrade: dist
        autoremove: yes
      when: ansible_os_family == "Debian"
      register: upgrade_result
      failed_when: false

    - name: "DNF: check-update (RedHat) - nur prüfen"
      command: dnf check-update
      when: ansible_os_family == "RedHat"
      register: simulate_dnf
      failed_when: false
      changed_when: false

    - name: "DNF: Upgrade durchführen (RedHat)"
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      register: upgrade_result
      failed_when: false

    - name: "Prüfen ob Reboot erforderlich"
      stat:
        path: /var/run/reboot-required
      register: reboot_file
      failed_when: false

    - name: "Setze Host-Zusammenfassung als Fact"
      set_fact:
        host_update_summary:
          host: "{{ inventory_hostname }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          changed: "{{ (upgrade_result.changed | default(false)) | bool }}"
          failed: "{{ (upgrade_result.failed | default(false)) | bool }}"
          reboot_required: "{{ reboot_file.stat.exists | default(false) }}"
          pkg_preview: >-
            {% if ansible_os_family == 'Debian' and apt_update_result is defined %}
              {{ (apt_update_result.stdout_lines | default([]))[:max_pkg_preview] | join(', ') }}
            {% elif ansible_os_family == 'RedHat' and simulate_dnf is defined %}
              {{ (simulate_dnf.stdout_lines | default([]))[:max_pkg_preview] | join(', ') }}
            {% else %}
              keine Paketinfo
            {% endif %}
      no_log: false

    - name: "Debug: Host-Zusammenfassung (nur Joblog)"
      debug:
        var: host_update_summary

- name: "Sammle nur Hosts mit Änderungen und sende ein zusammenfassendes Discord-Message (run_once)"
  hosts: localhost
  gather_facts: no
  run_once: true

  tasks:
    - name: "Stelle sicher, dass discord_webhook gesetzt ist"
      assert:
        that:
          - discord_webhook is defined
        fail_msg: "discord_webhook ist nicht gesetzt. Lege die Webhook-URL in Inventory-Variablen oder als extra var fest."

    - name: "Baue Liste der Hosts mit Änderungen"
      set_fact:
        changed_hosts: "{{ changed_hosts | default([]) + [ single_line ] }}"
      vars:
        single_line: >-
          **{{ hostvars[item].host_update_summary.host }}** — {{ hostvars[item].host_update_summary.os }}
          {% if hostvars[item].host_update_summary.reboot_required %} — 🔁 Reboot erforderlich{% endif %}
          {% if hostvars[item].host_update_summary.pkg_preview is defined and hostvars[item].host_update_summary.pkg_preview != 'keine Paketinfo' %}\nPackages: {{ hostvars[item].host_update_summary.pkg_preview }}{% endif %}
      loop: "{{ groups['all'] }}"
      loop_control:
        label: "{{ item }}"
      when: hostvars[item].host_update_summary is defined and hostvars[item].host_update_summary.changed

    - name: "Wenn keine geänderten Hosts, setze Hinweis"
      set_fact:
        changed_hosts: ["Keine Änderungen auf den Hosts festgestellt."]
      when: changed_hosts is not defined or changed_hosts | length == 0

    - name: "Baue Discord-Payload (nur eine Nachricht)"
      set_fact:
        discord_payload:
          content: "Update Summary ({{ lookup('pipe','date +%F') }})"
          embeds:
            - title: "Update Summary"
              description: "Nur Hosts mit Updates (falls vorhanden)"
              fields:
                - name: "Anzahl geänderter Hosts"
                  value: "{{ (changed_hosts | length) if (changed_hosts is defined and (changed_hosts | first) != 'Keine Änderungen auf den Hosts festgestellt.') else 0 }}"
                  inline: true
                - name: "Details"
                  value: "{{ changed_hosts | join('\\n') }}"
                  inline: false
              timestamp: "{{ lookup('pipe','date --iso-8601=seconds') }}"

    - name: "Sende Summary an Discord Webhook"
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: "{{ discord_payload | to_json }}"
        status_code: [200,204]
        body_format: json
      register: discord_result
      failed_when: discord_result.status not in [200,204]

    - name: "Debug: Discord Ergebnis"
      debug:
        var: discord_result
